image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    # SPA fallback: 404.html = index.html
    - cp dist/index.html dist/404.html
    # GitLab Pages ожидает папку public/
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main   # или master — в зависимости от твоей ветки
