image: node:20

pages:
  stage: deploy
  script:
    - cd abz.agency
    - npm ci
    - npm run build
    - cp dist/index.html dist/404.html
    - mv dist ../public
  artifacts:
    paths:
      - public
  only:
    - main
