
image: node:20

variables:
  ROLLUP_DISABLE_NATIVE: 'true'   
pages:
  stage: deploy
  script:
  - cd abz.agency
  - npm ci
  - npm run build
  - mv dist ../public

  artifacts:
    paths:
      - public
  only:
    - main
