image: node:lts

variables:
  ROLLUP_DISABLE_NATIVE: '1'   # отключаем нативный rollup

pages:
  stage: deploy
  script:
    - cd abz.agency
    - node -v && npm -v
    - echo "VITE_BASE_PATH=$VITE_BASE_PATH"
    - rm -rf node_modules
    # если есть lockfile -> npm ci, иначе обычная установка
    - if [ -f package-lock.json ]; then npm ci; else npm install --no-audit --no-fund; fi
    - npm run build
    - mv dist ../public
  artifacts:
    paths:
      - public
  only:
    - main
