
image: node:22

variables:

  VITE_BASE_PATH: "/${CI_PROJECT_NAME}/"

stages: [deploy]

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - abz.agency/node_modules/

pages:
  stage: deploy
  script:
    - cd abz.agency
    - npm ci
    - ROLLUP_DISABLE_NATIVE=1 npm run build
    - mv dist ../public
  artifacts:
    paths: [public]
    expire_in: 7 days
  only: [main]
