image: node:22

stages: [deploy]

variables:
  ROLLUP_SKIP_NODEJS_NATIVE: "1"   # <- ключевая строчка
  VITE_BASE_PATH: "/${CI_PROJECT_NAME}/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - abz.agency/node_modules/

pages:
  stage: deploy
  script:
    - cd abz.agency
    - npm ci
    - npm run build
    - mv dist ../public
  artifacts:
    paths: [public]
  only: [main]
