image: node:22.12-bookworm

variables:
  # Vite/Pages
  VITE_BASE_PATH: "/$CI_PROJECT_NAME/"
  # чтобы не ставил нативный rollup, если вдруг
  ROLLUP_DISABLE_NATIVE: "1"
  NPM_CONFIG_AUDIT: "false"
  NPM_CONFIG_FUND: "false"

pages:
  stage: deploy
  script:
    - cd abz.agency
    - node -v && npm -v
    - echo "VITE_BASE_PATH=$VITE_BASE_PATH"
    # НЕ удаляем package-lock.json
    - rm -rf node_modules
    - npm ci
    - npm run build
    - mv dist ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
