# .gitlab-ci.yml (лежит в test_task/.gitlab-ci.yml)
image: node:lts

variables:
  # принудительно JS-версия rollup (без нативных бинарников)
  ROLLUP_DISABLE_NATIVE: "1"
  # базовый путь для GitLab Pages — /<имя_проекта>/
  VITE_BASE_PATH: "/$CI_PROJECT_NAME/"
  NPM_CONFIG_AUDIT: "false"
  NPM_CONFIG_FUND: "false"

pages:
  stage: deploy
  script:
    - cd abz.agency
    - node -v && npm -v
    - echo "ROLLUP_DISABLE_NATIVE=$ROLLUP_DISABLE_NATIVE"
    # подчистим возможный мусор, чтобы обойти баг npm с optional deps
    - rm -rf node_modules package-lock.json
    - npm ci
    - npm run build
    # SPA-роутинг на GitLab Pages
    - cp dist/index.html dist/404.html || true
    - mv dist ../public
  artifacts:
    paths:
      - public
  only:
    - main
